### ISSUE TITLE
Correct behavior outside of RStudio

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation#43]
If you now use `RDocumentation` outside of RStudio, the URL that opens does not render correctly. The package should work fine both inside and outside of RStudio.

We can use 

```R
isTRUE(Sys.getenv("RSTUDIO") == "1")
```

To check if R is being executed inside RStudio, probably in the `view_help()` function.

@ludov04 Is there an easy way to default to the normal RDocumentation page, like you would get when you go to rdocumentation.org. I wouldn't bother trying to send code to the console like it is now in RStudio.

**Comment by ludov04** [comment]
I think the rendering can be easily fixable on the rdocumentation.org side (that would not require an update of the package) but the url will still be `127.0.0.1:.../library/RDocumentation/doc/index.html`. 

Is that workable if we fix it like that so that's working and we can later fix it properly to open in www.rdocumentation.org (that would need a bit more work both on the package and the app side)

**Comment by filipsch** [comment]
@ludov04 you're right. Will be fixed if [this RDocumentation-app issue](https://github.com/datacamp/RDocumentation-app/issues/272) is fixed.

**Comment by filipsch** [comment]
Fixed now.
