### ISSUE TITLE
Dont work for me R 3.3.1 and latest RStudio

### ISSUE THREAD

**Issue by TuSKan** [datacamp/RDocumentation#44]

**Comment by lordbitin** [comment]
+1

Does not work in R 3.3.0 with RStudio Server '.99.892

**Comment by filipsch** [comment]
@TuSKan @lordbitin
Could you explain what the exact issue is? Nothing happens? There are errors?
Thanks for raising this issue.

**Comment by ludov04** [comment]
@TuSKan @lordbitin Can you provide more details about your system ? On what OS are you ?

**Comment by lordbitin** [comment]
Hi,

Sorry for not giving more details about the error.

The problem is that I try to execute a help command, let's say, `?kmeans`, and this is what I see in the Help View Pane:

![image](https://cloud.githubusercontent.com/assets/7083752/19390168/31e0ba96-9227-11e6-94ef-7199b66b263b.png)

Blank page.

I am running R 3.3.0 in RStudio Server 0..99.892, over CentOS 7 (release 7.2.1511)

Thanks!

**Comment by ludov04** [comment]
Thanks for theses additionals details, we'll look into it and keep you informed

**Comment by TuSKan** [comment]
I'm on Windows 10, R3.3.1 and RStudio v1.0.40 Preview

![rdocument_rstudio_bug](https://cloud.githubusercontent.com/assets/10839799/19406166/4d4fcb3e-9257-11e6-91c9-ba714841258a.jpg)

**Comment by filipsch** [comment]
@TuSKan @lordbitin this should be solved for both platforms now!
