### ISSUE TITLE
Help functions not using RDocumentation

### ISSUE THREAD

**Issue by Raesu** [datacamp/RDocumentation#77]
I just installed the package in RStudio. It is loaded with `library` and saw confirmation it is loaded with `search()`.

I have internet connectivity, but running things like `?lm` and `?t.test` still bring up the standard documentation. I restarted RStudio but with no effect. Also ran `enable_rdocs()`, no change.

My R and RStudio are all up to date. Did I miss something as to how this is supposed to work?

**Comment by filipsch** [comment]
@Raesu sorry for the late response here; this fell off our radar. There are clearly some issues with the RDocumentation package that we should fix; we'll look into it asap.

**Comment by joelcourtheyn** [comment]
I have the same problem.  However I guess there is interference with the package utils as I obtain the following warning after having loaded the Rdocumentation package
> library("RDocumentation", lib.loc="~/R/win-library/3.5")
Attaching package: ‘RDocumentation’
The following objects are masked from ‘package:utils’:
    ?, help, help.search

**Comment by filipsch** [comment]
@joelcourtheyn cc @Raesu can you verify that you have the latest version of the RDocumentation package installed? We've simplified it a great deal, which should reduce the amount of edge cases.

@joelcourtheyn it is normal that some objects are masked, as we are overriding the standard definition, so this is expected behavior.

**Comment by joelcourtheyn** [comment]
Dear,

I verified that I had the latest version of package RDocumentation (namely 0.8.2).

Could you give any hint ?

Kind regards

 

Met vriendelijke groeten,

Joël Courtheyn

joel.courtheyn@telenet.be

 

 

 

Van: Filip Schouwenaars [mailto:notifications@github.com] 
Verzonden: maandag 14 mei 2018 9:06
Aan: datacamp/RDocumentation
CC: Joel Courtheyn; Mention
Onderwerp: Re: [datacamp/RDocumentation] Help functions not using RDocumentation (#77)

 

@joelcourtheyn <https://github.com/joelcourtheyn>  cc @Raesu <https://github.com/Raesu>  can you verify that you have the latest version of the RDocumentation package installed? We've simplified it a great deal, which should reduce the amount of edge cases.

@joelcourtheyn <https://github.com/joelcourtheyn>  it is normal that some objects are masked, as we are overriding the standard definition, so this is expected behavior.

**Comment by filipsch** [comment]
@joelcourtheyn I tried to debug locally, and indeed, it's not showing up as it should. It has to do with the request that is sent to the RDocumentation Node app to get the help payload. We'll look into it asap. Until then, please use the online RDocumentation docs. Thanks!

**Comment by filipsch** [comment]
@joelcourtheyn It should be fixed if you install the latest development version:

```
library(remotes) # or library(devtools)
install_github("datacamp/RDocumentation")
library(RDocumentation)
?mean
```

**Comment by joelcourtheyn** [comment]
Ok, I implemented your latest version and it is OK.  Thanks
